# https://pre-commit.com/
# https://pre-commit.com/hooks.html

# my use case:
# - muzimuzhi/latex-zutil
#   https://github.com/muzimuzhi/latex-zutil/blob/main/.pre-commit-config.yaml

# required by "language: unsupported" hooks
minimum_pre_commit_version: "4.4.0"

# https://pre-commit.ci/#configuration
ci:
  skip: [check-spelling]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  # run "pre-commit autoupdate --freeze" to update the version
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/kjanat/actionlint
  rev: 733ac2f73f6d80c269aa7a02d1ee83673fa5ab33  # frozen: v1.16
  hooks:
  - id: actionlint
# https://check-jsonschema.readthedocs.io/en/latest/precommit_usage.html#check-github-actions
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 12e63946db2c5cfcc9030fac21c3883ba88c6ed8  # frozen: 0.38.0
  hooks:
    - id: check-github-actions
      files: ^[^\.]*/action\.ya?ml$
      # args: ['--verbose']
- repo: local
  hooks:
  # typos bumps version frequently, so use system installation instead of the
  # official pre-commit hook
  # https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md
  # https://github.com/crate-ci/typos/blob/master/.pre-commit-hooks.yaml
  - id: check-spelling
    alias: typos
    name: Check spelling
    language: unsupported
    # same as the official `typos` hook args
    # https://github.com/crate-ci/typos/blob/ebc6aac34e3692b3ce373e13f4145e8980875396/.pre-commit-hooks.yaml
    entry: typos --write-changes --force-exclude
# https://pre-commit.com/#meta-hooks
# "pre-commit run --hook-stage manual"
- repo: meta
  hooks:
  - id: check-hooks-apply
    stages: [manual]
  - id: check-useless-excludes
    stages: [manual]
  # "pre-commit run identity --hook-stage manual -a" prints all files not
  # excluded
  - id: identity
    stages: [manual]
